### PR TITLE
Jbrewer

### PR DESCRIPTION
**Pull request by nuyarralek**
I moved a bunch of files into a src folder. I added a tests folder and created a simply unit test using pytest library.

### CODE REVIEW

**Comment by mgear2** [comment]
Nice! 

I did notice one bug: the README image links need to be updated to point to the new `src/data` folder. Also does the `.metals` folder need to be in the repo?

**Comment by nuyarralek** [comment]
I don't think so, I don't know what the .metals folder is, I was going to
ask you about it lol

**Comment by mgear2** [comment]
The .metals folder only shows up in this branch; it may have just gotten committed accidentally.

**Comment by nuyarralek** [comment]
Hmm ok I just don't know what it is

**Comment by nuyarralek** [comment]
I fixed the README and removed the .metals folder

**Review by jzcs — APPROVED** [review]
Approved!!

**Comment by mgear2** [comment]
Everything was fixed, just the undervoid title image in the README had a small typo so it wasn't showing correctly. I fixed it and will merge shortly.

**Pull request merged**
